name = "pals"
uuid = "05302d2e-dc94-4a43-8277-9ca7ef3c80e8"  
authors = ["Alex He <adh236@cornell.edu>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]